<%@ page import="com.hotel.reservation.domain.model.Bill" %>
<%
    Bill bill = (Bill) request.getAttribute("bill");
%>

<!DOCTYPE html>
<html>
<head>
    <title>Invoice | Hotel Reservation</title>

    <link rel="stylesheet"
          href="${pageContext.request.contextPath}/assets/css/style.css">

    <style>
        /* ===== INVOICE STYLES ===== */
        .invoice-container {
            max-width: 700px;
            margin: 80px auto;
            background: #fff;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0,0,0,0.15);
        }

        .invoice-header {
            text-align: center;
            margin-bottom: 30px;
        }

        .invoice-header h2 {
            margin-bottom: 5px;
        }

        .invoice-header p {
            color: #555;
            font-size: 14px;
        }

        .invoice-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .invoice-table th,
        .invoice-table td {
            padding: 12px;
            border-bottom: 1px solid #ddd;
            text-align: left;
        }

        .invoice-table th {
            background: #f4f6f8;
        }

        .invoice-total {
            margin-top: 25px;
            text-align: right;
            font-size: 18px;
            font-weight: bold;
        }

        .invoice-footer {
            margin-top: 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .print-btn {
            padding: 10px 20px;
            background: #1e3c72;
            color: #fff;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            font-size: 14px;
        }

        .print-btn:hover {
            background: #16315c;
        }

        /* ===== PRINT MODE ===== */
        @media print {
            body {
                background: #fff;
            }
            .print-btn {
                display: none;
            }
            .invoice-container {
                box-shadow: none;
                margin: 0;
            }
        }
    </style>
</head>

<body>

<div class="invoice-container">

    <!-- HEADER -->
    <div class="invoice-header">
        <h2>Hotel Reservation Invoice</h2>
        <p>Thank you for choosing our hotel</p>
    </div>

    <!-- BILL DETAILS -->
    <table class="invoice-table">
        <tr>
            <th>Reservation ID</th>
            <td><%= bill.getReservationId() %></td>
        </tr>
        <tr>
            <th>Number of Nights</th>
            <td><%= bill.getNights() %></td>
        </tr>
        <tr>
            <th>Room Rate (per night)</th>
            <td><%= bill.getRoomRate() %></td>
        </tr>
        <tr>
            <th>Payment Method</th>
            <td><%= bill.getPaymentMethod() %></td>
        </tr>
    </table>

    <!-- TOTAL -->
    <div class="invoice-total">
        Total Amount: <%= bill.getTotalAmount() %>
    </div>

    <!-- FOOTER -->
    <div class="invoice-footer">
        <span>Generated by Hotel Reservation System</span>
        <button class="print-btn" onclick="window.print()">Print Invoice</button>
    </div>

</div>

</body>
</html>
