<%@ page session="true" %>
<%@ page import="com.hotel.reservation.domain.model.Bill" %>

<%
    Bill bill = (Bill) request.getAttribute("bill");
%>

<!DOCTYPE html>
<html>
<head>
    <title>Invoice | Hotel Reservation</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        @media print {
            aside, header, .print-btn {
                display: none !important;
            }
            body {
                background: white !important;
            }
        }
    </style>
</head>

<body class="bg-gray-100 font-sans">

<div class="flex h-screen">

    <jsp:include page="includes/sidebar.jsp" />


        <!-- ===== PAGE CONTENT ===== -->
        <main class="flex-1 overflow-y-auto p-10">

            <div class="max-w-3xl mx-auto bg-white shadow-2xl rounded-3xl p-10">

                <!-- Invoice Header -->
                <div class="text-center mb-10">
                    <h1 class="text-3xl font-bold text-gray-800">
                        Hotel Reservation Invoice
                    </h1>
                    <p class="text-gray-500 mt-2">
                        Thank you for choosing our hotel
                    </p>
                </div>

                <!-- Invoice Details -->
                <div class="space-y-6">

                    <div class="flex justify-between border-b pb-4">
                        <span class="text-gray-600">Reservation ID</span>
                        <span class="font-semibold text-gray-800">
                            <%= bill.getReservationId() %>
                        </span>
                    </div>

                    <div class="flex justify-between border-b pb-4">
                        <span class="text-gray-600">Number of Nights</span>
                        <span class="font-semibold text-gray-800">
                            <%= bill.getNights() %>
                        </span>
                    </div>

                    <div class="flex justify-between border-b pb-4">
                        <span class="text-gray-600">Room Rate (per night)</span>
                        <span class="font-semibold text-gray-800">
                            LKR <%= bill.getRoomRate() %>
                        </span>
                    </div>

                    <div class="flex justify-between border-b pb-4">
                        <span class="text-gray-600">Payment Method</span>
                        <span class="font-semibold text-gray-800">
                            <%= bill.getPaymentMethod() %>
                        </span>
                    </div>

                </div>

                <!-- Total -->
                <div class="mt-10 text-right">
                    <div class="text-xl font-bold text-indigo-600">
                        Total Amount: LKR <%= bill.getTotalAmount() %>
                    </div>
                </div>

                <!-- Footer -->
                <div class="mt-12 flex justify-between items-center">

                    <span class="text-gray-400 text-sm">
                        Generated by Hotel Reservation System
                    </span>

                    <button class="print-btn bg-indigo-600 text-white px-6 py-3 rounded-xl hover:bg-indigo-700 transition shadow-lg"
                            onclick="window.print()">
                        Print Invoice
                    </button>

                </div>

            </div>

        </main>

    </div>

</div>

</body>
</html>